apiVersion: v1
kind: Service
metadata:
  name: jenkins-docker
  labels:
   app: jenkins
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    nodePort: 31002
  selector:
    app: jenkins


